give @s gacha:gacha_coin
give @s gacha:gacha_coin_mega
give @s gacha:pokeball_capsule
give @s gacha:mega_capsule
give @s gacha:wild_capsule
give @s gacha:ultraball_capsule
give @s gacha:superball_capsule
give @s gacha:masterball_capsule
give @s serp:gacha_machine_black
give @s serp:gacha_machine
give @s serp:gacha_machine_light_gray
give @s serp:gacha_machine_blue
give @s serp:gacha_machine_cyan
give @s serp:gacha_machine_lime
give @s serp:gacha_machine_gray
give @s serp:gacha_machine_brown
give @s serp:gacha_machine_light_blue
give @s serp:gacha_machine_green
give @s serp:gacha_machine_orange
give @s serp:megagacha_machine
give @s serp:gacha_machine_white
give @s serp:gacha_machine_magenta
give @s serp:gacha_machine_purple
give @s serp:gacha_machine_red
give @s serp:gacha_machine_yellow
give @s serp:gacha_machine_pink
give @s serp:wildgacha_machine
give @s serp:megagacha_machine_black
