give @s po:gilded_chest
give @s serp:blue_feather_offering
give @s serp:box_offering
give @s serp:box_treat_offering
give @s serp:apicot_berry
give @s serp:dialga_offering1
give @s serp:cosmicdust_offering
give @s serp:dialga_offering
give @s serp:dialga_offering2
give @s serp:ganlon_berry
give @s serp:ideals_offering
give @s serp:lansat_berry
give @s serp:haban_berry
give @s serp:occa_berry
give @s serp:liechi_berry
give @s serp:entei_treat_offering
give @s serp:passho_berry
give @s serp:palkia_offering2
give @s serp:pearl_of_justice_offering
give @s serp:payapa_berry
give @s serp:petaya_berry
give @s serp:raikou_treat_offering
give @s serp:palkia_offering
give @s serp:palkia_offering1
give @s serp:red_feather_offering
give @s serp:salac_berry
give @s serp:struth_offering
give @s serp:star_candy
give @s serp:suicune_treat_offering
give @s serp:wacan_berry
give @s serp:wepear_berry
give @s serp:reshiram_offering1
give @s serp:zekrom_offering1
give @s serp:yellow_feather_offering
