give @s serp:aerodactylite_ore
give @s serp:absolite_ore
give @s serp:alakazite
give @s serp:absolite
give @s serp:aerodactylite
give @s serp:apricorn_black
give @s serp:ampharosite
give @s serp:apricorn_green
give @s serp:ampharosite_ore
give @s serp:anistarite_crystal
give @s serp:alakazite_ore
give @s serp:apricorn_pink
give @s serp:apricorn_blue
give @s serp:apricorn_yellow
give @s serp:apricorn_red
give @s serp:banettite_ore
give @s serp:beedrillite_ore
give @s serp:banettite
give @s serp:apricorn_white
give @s serp:beedrillite
give @s serp:badge
give @s serp:beetroot_ponigiri
give @s serp:black_cooking_pot
give @s serp:big_malasada
give @s serp:black_glasses
give @s serp:blastoisinite
give @s serp:black_cooking_pot_item
give @s serp:black_edible_dye
give @s serp:berry_jam_ponigiri
give @s serp:blue_cooking_pot_item
give @s serp:blazikenite
give @s serp:blue_cooking_pot
give @s serp:blastoisinite_ore
give @s serp:blue_mint_leaf
give @s serp:blue_edible_dye
give @s serp:blue_mint_seeds
give @s serp:blazikenite_ore
give @s serp:candied_apple10
give @s serp:candied_apple
give @s serp:brown_edible_dye
give @s serp:blue_prism_ore
give @s serp:brown_mushroom_ponigiri
give @s serp:candied_apple12
give @s serp:candied_apple11
give @s serp:blue_prism
give @s serp:candied_apple14
give @s serp:candied_apple15
give @s serp:candied_apple16
give @s serp:candied_apple5
give @s serp:candied_apple13
give @s serp:candied_apple2
give @s serp:candied_apple4
give @s serp:candied_apple3
give @s serp:candied_apple7
give @s serp:charizardite_x_ore
give @s serp:candied_apple8
give @s serp:carrot_ponigiri
give @s serp:charizardite_x
give @s serp:candied_apple9
give @s serp:candied_apple6
give @s serp:cyan_mint_seeds
give @s serp:common_ticket
give @s serp:charizardite_y
give @s serp:cyan_edible_dye
give @s serp:dawn_stone
give @s serp:charizardite_y_ore
give @s serp:cyan_mint_leaf
give @s serp:dusk_stone_block
give @s serp:dynamax_band
give @s serp:dried_kelp_ponigiri
give @s serp:dusk_stone
give @s serp:dawn_stone_block
give @s serp:dynamax_band_black
give @s serp:dynamax_band_lime
give @s serp:dynamax_band_blue
give @s serp:dynamax_candy_l
give @s serp:dynamax_candy
give @s serp:dynamax_candy_m
give @s serp:dynamax_band_white
give @s serp:dynamax_band_red
give @s serp:dynamax_band_pink
give @s serp:dynamax_band_yellow
give @s serp:dynamax_band_purple
give @s serp:fire_stone
give @s serp:egg_ponigiri
give @s serp:fire_stone_block
give @s serp:dynamax_candy_xl
give @s serp:enigma_berry
give @s serp:galarica_nuts_bush
give @s serp:epic_ticket
give @s serp:galarica_nuts
give @s serp:garchompite_ore
give @s serp:galladite_ore
give @s serp:gardevoirite_ore
give @s serp:galladite
give @s serp:galarica_nuts_grass_item
give @s serp:gardevoirite
give @s serp:gengarite
give @s serp:garchompite
give @s serp:green_prism
give @s serp:gray_edible_dye
give @s serp:gengarite_ore
give @s serp:gold_helmet
give @s serp:green_mint_leaf
give @s serp:golden_carrot_ponigiri
give @s serp:green_mint_seeds
give @s serp:green_edible_dye
give @s serp:greninjite
give @s serp:green_prism_ore
give @s serp:gyaradosite_ore
give @s serp:gyaradosite
give @s serp:hard_anistarite_crystal
give @s serp:greninjite_ore
give @s serp:hearty_gran_grass
give @s serp:hearty_grans
give @s serp:heracronite_ore
give @s serp:heracronite
give @s serp:jubilife_muffing
give @s serp:hearty_grans_grass_item
give @s serp:ice_stone_block
give @s serp:kangaskhanite_ore
give @s serp:kangaskhanite
give @s serp:ice_stone
give @s serp:key_stone
give @s serp:key_shard
give @s serp:light_gray_edible_dye
give @s serp:lime_cooking_pot
give @s serp:leaf_stone_block
give @s serp:key_shard_ore
give @s serp:light_blue_edible_dye
give @s serp:leaf_stone
give @s serp:lime_edible_dye
give @s serp:loot
give @s serp:lime_cooking_pot_item
give @s serp:lucarionite
give @s serp:lumiose_galette
give @s serp:lucarionite_ore
give @s serp:magenta_edible_dye
give @s serp:magma_cookie
give @s serp:mega_ring
give @s serp:mega_ring_glasses
give @s serp:mega_ring_blue
give @s serp:mega_ring_red
give @s serp:mega_ring_purple
give @s serp:mega_ring_pink
give @s serp:mega_ring_lime
give @s serp:minst_grass_placeable
give @s serp:mewtwonite_y_ore
give @s serp:mewtwonite_x
give @s serp:mewtwonite_x_ore
give @s serp:mewtwonite_y
give @s serp:mint_active
give @s serp:mega_ring_white
give @s serp:mega_ring_yellow
give @s serp:mint_bold
give @s serp:mint_affable
give @s serp:mint_crazy
give @s serp:mint_agitated
give @s serp:mint_chereful
give @s serp:mint_daring
give @s serp:mint_docile
give @s serp:mint_cautious
give @s serp:mint_kind
give @s serp:mint_gross
give @s serp:mint_mischievous
give @s serp:mint_firm
give @s serp:mint_loose
give @s serp:mint_modest
give @s serp:mint_placid
give @s serp:mint_naive
give @s serp:mint_rare
give @s serp:mint_serious
give @s serp:mint_strong
give @s serp:mint_scared
give @s serp:mint_sullen
give @s serp:mint_serene
give @s serp:mint_tame
give @s serp:mint_timid
give @s serp:mints_grass
give @s serp:moomoo_milk
give @s serp:orange_edible_dye
give @s serp:old_red_helmet
give @s serp:moon_stone
give @s serp:pewter_crunchies
give @s serp:moon_stone_block
give @s serp:pidgeotite
give @s serp:pink_edible_dye
give @s serp:pink_mint_seeds
give @s serp:pink_cooking_pot_item
give @s serp:poisonous_potato_ponigiri
give @s serp:pink_cooking_pot
give @s serp:pidgeotite_ore
give @s serp:ponigiri
give @s serp:pink_mint_leaf
give @s serp:potato_mochi
give @s serp:potato_ponigiri
give @s serp:rare_candy_m
give @s serp:purple_edible_dye
give @s serp:pumpkin_ponigiri
give @s serp:rare_candy
give @s serp:rare_candy_max
give @s serp:rare_candy_l
give @s serp:rare_candy_s
give @s serp:rare_ticket
give @s serp:raw_aerodactylite
give @s serp:rare_candy_xl
give @s serp:rare_candy_xs
give @s serp:raw_alakazite
give @s serp:raw_ampharosite
give @s serp:raw_absolite
give @s serp:raw_banettite
give @s serp:raw_blazikenite
give @s serp:raw_blastoisinite
give @s serp:raw_charizardite_x
give @s serp:raw_charizardite_y
give @s serp:raw_beedrillite
give @s serp:raw_beef_ponigiri
give @s serp:raw_blue_prism
give @s serp:raw_cod_ponigiri
give @s serp:raw_galladite
give @s serp:raw_chicken_ponigiri
give @s serp:raw_garchompite
give @s serp:raw_gardevoirite
give @s serp:raw_green_prism
give @s serp:raw_gengarite
give @s serp:raw_greninjite
give @s serp:raw_gyaradosite
give @s serp:raw_lucarionite
give @s serp:raw_mutton_ponigiri
give @s serp:raw_heracronite
give @s serp:raw_mewtwonite_x
give @s serp:raw_kangaskhanite
give @s serp:raw_mewtwonite_y
give @s serp:raw_pidgeotite
give @s serp:raw_sablenite
give @s serp:raw_scizorite
give @s serp:raw_rabbit_ponigiri
give @s serp:raw_sceptilite
give @s serp:raw_slowbronite
give @s serp:raw_red_prism
give @s serp:raw_salamencite
give @s serp:raw_porkchop_ponigiri
give @s serp:raw_venusaurite
give @s serp:red_mint_seeds
give @s serp:red_cooking_pot
give @s serp:raw_swampertite
give @s serp:red_edible_dye
give @s serp:red_mint_leaf
give @s serp:raw_steelixite
give @s serp:red_cooking_pot_item
give @s serp:red_mushroom_ponigiri
give @s serp:red_prism_ore
give @s serp:red_prism
give @s serp:rotomphone
give @s serp:rotomphone_black
give @s serp:rotomphone_blue
give @s serp:rotomphone_lime
give @s serp:rotomphone_pink
give @s serp:rotomphone_red
give @s serp:rotomphone_white
give @s serp:rotomphone_purple
give @s serp:rotten_flesh_ponigiri
give @s serp:sablenite
give @s serp:sablenite_ore
give @s serp:rotomphone_yellow
give @s serp:salamancite_ore
give @s serp:salamencite
give @s serp:sceptilite
give @s serp:scizorite
give @s serp:scizorite_ore
give @s serp:shiny_stone_block
give @s serp:salmon_ponigiri
give @s serp:shiny_stone
give @s serp:sceptilite_ore
give @s serp:slowbronite
give @s serp:slowbronite_ore
give @s serp:slowpoke_tail
give @s serp:smoked_tail_curry
give @s serp:slowpoke_tail_ponigiri
give @s serp:steelixite_ore
give @s serp:steelixite
give @s serp:sugar_block
give @s serp:sun_stone_block
give @s serp:swamperite_ore
give @s serp:thunder_stone
give @s serp:swampertite
give @s serp:sun_stone
give @s serp:thunder_stone_block
give @s serp:uncommon_ticket
give @s serp:unrefined_hyperpotion
give @s serp:unrefined_superpotion
give @s serp:venusaurite_ore
give @s serp:water_stone
give @s serp:venusaurite
give @s serp:white_cooking_pot
give @s serp:water_stone_block
give @s serp:white_cooking_pot_item
give @s serp:unrefined_potion
give @s serp:white_edible_dye
give @s serp:wishing_shard_drill
give @s serp:yellow_cooking_pot
give @s serp:white_mint_seeds
give @s serp:wishing_star
give @s serp:yellow_cooking_pot_item
give @s serp:white_mint_leaf
give @s serp:wishing_shard
give @s serp:yellow_edible_dye
